repository:
   description: BIKA

labels:
  - name: automated-pr
    color: 1316F2
    description: An PR created by automation action
  - name: invalid
    color: FF0000
    description: PR is invalid and should be not merged
  - name: manually-fix-needed
    color: FF0000
    description: Sync PR requires manual fix
