repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ".*\\.vscode/"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: debug-statements
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.3
    hooks:
      - id: cspell

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.2
    hooks:
      - id: poetry-check
        args: ["--lock"]

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.7
    hooks:
      - id: djhtml
        args: [ "--tabwidth=2" ]
      - id: djcss
        args: [ "--tabwidth=2" ]
      - id: djjs
        args: [ "--tabwidth=2" ]

  - repo: https://github.com/pycqa/docformatter
    # Put actual version when this issue is closed
    # https://github.com/PyCQA/docformatter/issues/293
    rev: "eb1df347edd128b30cd3368dddc3aa65edcfac38"
    hooks:
      - id: docformatter

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: [
          "--fix",
        ]
