# Generated by Django 5.2 on 2025-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                ],
                default="student",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
