# Generated by Django 5.2 on 2025-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("student", "Student"),
                    ("lecturer", "Lecturer"),
                ],
                default="student",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
