# Generated by Django 5.2 on 2025-04-26 03:31

import django.db.models.deletion
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True,
                        verbose_name="modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "start",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Start time",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Deadline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True,
                        verbose_name="modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "In Backlog"),
                            ("ready", "Ready"),
                            ("in_progress", "In Progress"),
                            ("ready_for_review", "Ready for Review"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="backlog",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="assignment.assignment",
                        verbose_name="Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
